name: setup-bun
description: "Setup Bun.js - Cache dependencies - Install dependencies"
runs:
  using: "composite"
  steps:
    - name: Setup Bun.js
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.21

    - name: Install dependencies
      shell: bash
      if: steps.cache_dependencies.outputs.cache-hit != 'true'
      run: bun ci --ignore-scripts
